# -*- coding: utf-8 -*-
"""Gemini_API_Call

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCI4paPTsdN4kueE76DCQjLI3tfKMb9M
"""

from google import genai
from google.genai import types

client = genai.Client(api_key="AIzaSyCawtptt5sU-btIFmqSqgVB9fhexNNmc3M")

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents="Explain how AI works in a few words",
    config=types.GenerateContentConfig(
        temperature=1
    )
)

print(response.text)