# -*- coding: utf-8 -*-
"""Session 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFvl2xLnNXbNQNXZpCuiXUuTMf6lH7z9
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Load and prepare data
print("Loading and preparing data...")
df = pd.read_csv("FuelConsumption.csv")
data = df[['ENGINESIZE', 'CYLINDERS', 'FUELCONSUMPTION_COMB', 'CO2EMISSIONS']]

# Split feature data from target
X = data[['ENGINESIZE', 'CYLINDERS', 'FUELCONSUMPTION_COMB']]
y = data['CO2EMISSIONS']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the model
print("Training the model...")
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions and evaluate
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Coefficients: {model.coef_}')
print(f'Intercept: {model.intercept_:.2f}')
print(f'Mean Squared Error: {mse:.2f}')
print(f'R² Score: {r2:.2f}')

feature_names = ['ENGINESIZE', 'CYLINDERS', 'FUELCONSUMPTION_COMB']

while True:
    print("\n" + "="*50)
    print("CO2 EMISSION PREDICTION")
    print("="*50)

    try:
        # Get user input
        print("\nPlease enter the following vehicle details:")
        engine_size = float(input("Engine Size (L): "))
        cylinders = int(input("Number of Cylinders: "))
        fuel_consumption = float(input("Fuel Consumption (L/100km): "))

        # Create input array and make prediction
        user_input = np.array([[engine_size, cylinders, fuel_consumption]])
        prediction = model.predict(user_input)

        # Display result
        print("\n" + "="*50)
        print(f"PREDICTED CO2 EMISSIONS: {prediction[0]:.2f} g/km")
        print("="*50)

        # Show what the model learned
        print(f"\nModel learned: CO2 = {model.intercept_:.2f} ", end="")
        for i, (coef, feature) in enumerate(zip(model.coef_, feature_names)):
            sign = "+" if coef >= 0 else ""
            print(f"{sign} {coef:.2f}×{feature}", end=" ")
        print()

    except ValueError:
        print("Error: Please enter valid numbers!")
    except Exception as e:
        print(f"An error occurred: {e}")

    continue_pred = input("\nWould you like to make another prediction? (y/n): ").lower()
    if continue_pred != 'y':
        print("Thank you for using the CO2 Emission Predictor!")
        break