# -*- coding: utf-8 -*-
"""Speech_Recognition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1owCF3UBghjK-6eoPgNKH12Hm3LQGK6ZS
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install SpeechRecognition

import os
from pydub import AudioSegment
import speech_recognition as sr

def simple_audio_to_text(audio_path, language='en-US'):
    """
    Simple function to convert any audio file to text.

    Args:
        audio_path (str): Path to audio file
        language (str): Language code (default: 'fa-IR' for Persian)

    Returns:
        str: Transcribed text
    """
    # Convert to WAV if needed
    if not audio_path.lower().endswith('.wav'):
        audio = AudioSegment.from_file(audio_path)
        audio = audio.set_frame_rate(16000).set_channels(1)
        audio_path = "temp_audio.wav"
        audio.export(audio_path, format="wav")

    # Transcribe
    recognizer = sr.Recognizer()
    try:
        with sr.AudioFile(audio_path) as source:
            audio_data = recognizer.record(source)
            text = recognizer.recognize_google(audio_data, language=language)
            return text
    except Exception as e:
        print(f"Error: {e}")
        return ""

# Quick usage
if __name__ == "__main__":
    text = simple_audio_to_text("/content/t10.ogg")
    print(text)

